Update patch set 3
Change has been successfully rebased and submitted as 5e4add6919b4bdc626b3f6a37395097b8fd360fc

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: src/dawn/node/README.md
Insertions: 2, Deletions: 2.

@@ -73,13 +73,13 @@
 
 If this fails with the error message `TypeError: expander is not a function or its return value is not iterable`, try appending `--build=false` to the start of the `run-cts` command line flags.
 
-To test against SwiftShader (SW implementation of Vulkan) instead of the default Vulkan device, prefix `./tools/run run-cts` with `VK_ICD_FILENAMES=<swiftshader-cmake-build>/Linux/vk_swiftshader_icd.json`. For example:
+To test against SwiftShader (software implementation of Vulkan) instead of the default Vulkan device, prefix `./tools/run run-cts` with `VK_ICD_FILENAMES=<swiftshader-cmake-build>/Linux/vk_swiftshader_icd.json`. For example:
 
 ```sh
 VK_ICD_FILENAMES=<swiftshader-cmake-build>/Linux/vk_swiftshader_icd.json ./tools/run run-cts --bin=<path-build-dir> [WebGPU CTS query]
 ```
 
-To test against Lavapipe (mesa's SW implementation of Vulkan), similarly to SwiftShader, prefix `./tools/run run-cts` with `VK_ICD_FILENAMES=<lavapipe-install-dir>/share/vulkan/icd.d/lvp_icd.x86_64.json`. For example:
+To test against Lavapipe (mesa's software implementation of Vulkan), similarly to SwiftShader, prefix `./tools/run run-cts` with `VK_ICD_FILENAMES=<lavapipe-install-dir>/share/vulkan/icd.d/lvp_icd.x86_64.json`. For example:
 
 ```sh
 VK_ICD_FILENAMES=<lavapipe-install-dir>/share/vulkan/icd.d/lvp_icd.x86_64.json ./tools/run run-cts --bin=<path-build-dir> [WebGPU CTS query]
```


Patch-set: 3
Subject: Add documentation to Dawn Node for using Lavapipe
Status: merged
Commit: 5e4add6919b4bdc626b3f6a37395097b8fd360fc
Tag: autogenerated:gerrit:merged
Groups: 96279defd2458305a2f80dc068cb959621bbcba4
Label: Code-Review=+2, 2486cb03a0daa1714674c8548f8da1c5fa18f510 Gerrit User 1000257 <1000257@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Commit-Queue=+2, bf6b16e22cd7ca785c25cfe4dc628162fbc1bb0b Gerrit User 1000250 <1000250@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Auto-Submit=+1, 08988ce94b0f113422765620427fcef3eb1dcff0 Gerrit User 1000250 <1000250@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Kokoro=+1, 24cd3bf41d7796e0c3728477297e2d39b9f02b7f Gerrit User 1002476 <1002476@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: SUBM=+1, 5fc2e024de35df219fffa32f5517cf017055a162
Submission-id: 152823
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Code-Review: Gerrit User 1000257 <1000257@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Commit-Queue: Gerrit User 1000250 <1000250@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Auto-Submit: Gerrit User 1000250 <1000250@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Kokoro: Gerrit User 1002476 <1002476@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 1001737 \u003c1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd\u003e","operation":"REMOVE","reason":"Change was submitted"}