Update patch set 1
Patch Set 1:

This patch failed to be applied to dawn-linux and dawn-mac Chromium bots. The failed bots said: 

error: could not apply dbf9f7c3... Fix conflicts between ANGLE & Dawn's spirv-cross build config
hint: after resolving the conflicts, mark the corrected paths

Astin/Kai/Corentin, is there anything wrong? Otherwise, can we just merge this patch?

Patch-set: 1
Reviewer: Gerrit User 1000017 <1000017@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Commit-Queue=0