Summarize CTS failures as first line of first max-severity log
With Chromium-side changes to extract the summary (first line of the log
we send back), the output has some redundancy but should be able to
report the correct thing out to LUCI:

[4/6] webgpu:examples:TEMP_LOG_TEST,expect_is_important,1,single: failed unexpectedly 0.4776s (worker 1):
  webgpu:examples:TEMP_LOG_TEST,expect_is_important,1,single:
    - INFO: info
  --> EXPECTATION FAILED: **** This is the important log line for this test
          at GPUTest.expect (http://127.0.0.1:55889/third_party/webgpu-cts/src/common/framework/fixture.js:269:40)
          at RunCaseSpecific.fn (http://127.0.0.1:55889/third_party/webgpu-cts/src/webgpu/examples.spec.js:21:7)
  Unexpected exception while running webgpu:examples:TEMP_LOG_TEST,expect_is_important,1,single:
  Traceback (most recent call last):
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/gpu_integration_test.py", line 640, in _RunGpuTest
      self.RunActualGpuTest(url, args)
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/webgpu_cts_integration_test_base.py", line 394, in RunActualGpuTest
      self.fail(
    File "/Users/kainino/Library/Caches/.vpython-root/store/cpython+fa1ipv0hcetnii1ulq4856mmfk/contents/lib/python3.8/unittest/case.py", line 753, in fail
      raise self.failureException(msg)
  AssertionError: webgpu:examples:TEMP_LOG_TEST,expect_is_important,1,single: failed
    EXPECTATION FAILED: **** This is the important log line for this test
  Saving screenshot as artifact debug_screenshots/screenshot-2024-06-28-16-04-44-135285.png
  Traceback (most recent call last):
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/gpu_integration_test.py", line 640, in _RunGpuTest
      self.RunActualGpuTest(url, args)
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/webgpu_cts_integration_test_base.py", line 394, in RunActualGpuTest
      self.fail(
    File "/Users/kainino/Library/Caches/.vpython-root/store/cpython+fa1ipv0hcetnii1ulq4856mmfk/contents/lib/python3.8/unittest/case.py", line 753, in fail
      raise self.failureException(msg)
  AssertionError: webgpu:examples:TEMP_LOG_TEST,expect_is_important,1,single: failed
    EXPECTATION FAILED: **** This is the important log line for this test
[6/6] webgpu:examples:TEMP_LOG_TEST,expect_is_important,3,subcases: failed unexpectedly 0.5219s (worker 1):
  webgpu:examples:TEMP_LOG_TEST,expect_is_important,3,subcases:
    - INFO: subcase: a=0
      info
  --> EXPECTATION FAILED: subcase: a=0
      **** This is the important log line for this test
      Error: **** This is the important log line for this test
          at GPUTest.expect (http://127.0.0.1:55889/third_party/webgpu-cts/src/common/framework/fixture.js:269:40)
          at RunCaseSpecific.fn (http://127.0.0.1:55889/third_party/webgpu-cts/src/webgpu/examples.spec.js:33:7)
    - INFO: subcase: a=0
      OK
  Unexpected exception while running webgpu:examples:TEMP_LOG_TEST,expect_is_important,3,subcases:
  Traceback (most recent call last):
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/gpu_integration_test.py", line 640, in _RunGpuTest
      self.RunActualGpuTest(url, args)
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/webgpu_cts_integration_test_base.py", line 394, in RunActualGpuTest
      self.fail(
    File "/Users/kainino/Library/Caches/.vpython-root/store/cpython+fa1ipv0hcetnii1ulq4856mmfk/contents/lib/python3.8/unittest/case.py", line 753, in fail
      raise self.failureException(msg)
  AssertionError: webgpu:examples:TEMP_LOG_TEST,expect_is_important,3,subcases: failed
    EXPECTATION FAILED: **** This is the important log line for this test
  Saving screenshot as artifact debug_screenshots/screenshot-2024-06-28-16-04-45-099587.png
  Traceback (most recent call last):
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/gpu_integration_test.py", line 640, in _RunGpuTest
      self.RunActualGpuTest(url, args)
    File "/Users/kainino/src/chrome/src/content/test/gpu/gpu_tests/webgpu_cts_integration_test_base.py", line 394, in RunActualGpuTest
      self.fail(
    File "/Users/kainino/Library/Caches/.vpython-root/store/cpython+fa1ipv0hcetnii1ulq4856mmfk/contents/lib/python3.8/unittest/case.py", line 753, in fail
      raise self.failureException(msg)
  AssertionError: webgpu:examples:TEMP_LOG_TEST,expect_is_important,3,subcases: failed
    EXPECTATION FAILED: **** This is the important log line for this test

Bug: 347963252
Change-Id: I7347ecf6a0a2d5f87434e942cc213fcb7a01de0e