Remove unnecessary ~Adapter destructor.
This destructor causes -Wdeprecated-copy-dtor to warn, because classes
with user-declared destructors should not have implicitly-generated copy
constructor and assignment. The destructor itself does nothing useful
(just clears a member that is going out of scope regardless); removing
it is simpler than implementing copy/assignment methods.

 ../../../../../../skia/third_party/externals/dawn/src/include\dawn_native/DawnNative.h(94,9): error: definition of implicit copy assignment operator for 'Adapter' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-dtor]
         ~Adapter();
         ^
 ../../../../../../skia/third_party/externals/dawn/src/include\dawn_native/DawnNative.h(90,30): note: in implicit copy assignment operator for 'dawn_native::Adapter' first required here
     class DAWN_NATIVE_EXPORT Adapter {
                              ^
 ../../../../../../skia/third_party/externals/dawn/src/include\dawn_native/DawnNative.h(90,11): note: due to 'Adapter' being dllexported
     class DAWN_NATIVE_EXPORT Adapter {
           ^
 ../../../../../../skia/third_party/externals/dawn/src/include\dawn_native/dawn_native_export.h(21,51): note: expanded from macro 'DAWN_NATIVE_EXPORT'
 #            define DAWN_NATIVE_EXPORT __declspec(dllexport)

Change-Id: I9c274c8dc71f06d9a57edc80ca4bd44c066290d8