dawn/native/d3d12: improve constexpr compatability with clang
In Mach engine we compile Dawn's d3d12 backend using Zig as a C/C++ compiler,
effectively clang. Unfortunately, this `static constexpr` fails to compile with
clang in `-std=c++17` mode:

```
error: constexpr variable 'kD3D12PromotableReadOnlyStates' must be initialized by a constant expression
```

I am not super familiar with C++ constexpr, there may be a better fix for this (and if so,
happy to learn) - but I suspect this is just some difference between clang and msvc. Having
this just be `static` instead of `static constexpr` doesn't seem too harmful, and lets
folks compile the d3d12 backend with clang/zig.

Signed-off-by: Stephen Gutekanst <stephen@hexops.com>
Change-Id: I772f1cb7e2b4f1b200820cd50f6b7df45850abbb