Update patch set 3
Patch Set 3:

Failed builds:
  luci.chromium.try/win-dawn-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8872067012363933088
    #### Step _compile (with patch)_ failed. Error logs are shown below:
    ```
    [638/8876] CXX obj/skia/skia/GrDawnTexture.obj
    FAILED: obj/skia/skia/GrDawnTexture.obj
    C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
    ../../third_party/skia/src/gpu/dawn/GrDawnTexture.cpp(160,19): error: no member named 'bytesPerRow' in 'wgpu::BufferCopyView'
    srcBuffer.bytesPerRow = 0; // TODO: remove this once the deprecated fields have been removed.
    ~~~~~~~~~ ^
    1 error generated.
    [702/8876] CXX obj/skia/skia/GrDawnGpu.obj
    FAILED: obj/skia/skia/GrDawnGpu.obj
    C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.chromium.try/win-dawn-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8872066383290861504
    #### Step _compile (with patch)_ failed. Error logs are shown below:
    ```
    [1654/12012] CXX obj/skia/skia/GrDawnTexture.obj
    FAILED: obj/skia/skia/GrDawnTexture.obj
    C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
    ../../third_party/skia/src/gpu/dawn/GrDawnTexture.cpp(160,19): error: no member named 'bytesPerRow' in 'wgpu::BufferCopyView'
    srcBuffer.bytesPerRow = 0; // TODO: remove this once the deprecated fields have been removed.
    ~~~~~~~~~ ^
    1 error generated.
    [1675/12012] CXX obj/skia/skia/GrDawnGpu.obj
    FAILED: obj/skia/skia/GrDawnGpu.obj
    C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1000002 \u003c1000002@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd\u003e","operation":"ADD","reason":"reviewer or cc replied"}