Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.chromium.try/linux-dawn-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8841018824159865152
    Step('test_pre_run (retry shards with patch).missing failed shards') (retcode: 1)
  luci.chromium.try/linux-dawn-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8841014419911784048
    #### Step _compile (with patch)_ failed. Error logs are shown below:
    ```
    [2727/2760] CXX obj/third_party/blink/renderer/core/core/js_event_handler.o
    FAILED: obj/third_party/blink/renderer/core/core/js_event_handler.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../third_party/blink/renderer/bindings/core/v8/js_event_handler.cc:108:32: error: unknown type name 'IDLStringV2'; did you mean 'IDLString'?
    ToV8Traits<IDLStringV2>::ToV8(script_state_of_listener,
    ^~~~~~~~~~~
    IDLString
    ../../third_party/blink/renderer/bindings/core/v8/idl_types.h:149:7: note: 'IDLString' declared here
    using IDLString = IDLStringBase<bindings::IDLStringConvMode::kDefault>;
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cv