[dawn] Disable tests due to validation layer failures
The current validation layers roll has caused the
`SwapChainTests.SwitchingDevice` tests to trigger:

```
Error: UNASSIGNED-Threading-Info: Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x4ea00000004ea, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x5d6b67e2 | Couldn't find VkSwapchainKHR Object 0x4ea00000004ea. This should not happen and may indicate a bug in the application.
```

Bug: dawn:2116
Change-Id: I3921648b1344093825b450b41210399810d430b1