Revert "Adds error promoting to device loss when disallowed error occurs in a scope."
This reverts commit 53893a3d774be0417642af5e0308d5bd327f5c2d.

Reason for revert: Breaking the roll into Chrome

```
../../third_party/googletest/src/googlemock/include/gmock/gmock-actions.h:679:11: error: call to implicitly-deleted copy constructor of 'std::unique_ptr<dawn::native::ErrorData>'
        : value_before_cast_(*value),
          ^                  ~~~~~~
../../third_party/googletest/src/googlemock/include/gmock/gmock-actions.h:660:26: note: in instantiation of member function 'testing::internal::ReturnAction<std::unique_ptr<dawn::native::ErrorData>>::Impl<std::unique_ptr<dawn::native::ErrorData>, Result<void, dawn::native::ErrorData> (unsigned int, dawn::native::CommandBufferBase *const *)>::Impl' requested here
    return Action<F>(new Impl<R, F>(value_));
                         ^
../../third_party/dawn/src/dawn/tests/unittests/native/AllowedErrorTests.cpp:78:19: note: in instantiation of function template specialization 'testing::internal::ReturnAction<std::unique_ptr<dawn::native::ErrorData>>::operator Action<Result<void, dawn::native::ErrorData> (unsigned int, dawn::native::CommandBufferBase *const *)>' requested here
        .WillOnce(Return(DAWN_OUT_OF_MEMORY_ERROR(kOomErrorMessage)));
                  ^
../../buildtools/third_party/libc++/trunk/include/__memory/unique_ptr.h:210:59: note: copy constructor is implicitly deleted because 'unique_ptr<dawn::native::ErrorData>' has a user-declared move constructor
  _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_SINCE_CXX23 unique_ptr(unique_ptr&& __u) _NOEXCEPT
```

Original change's description:
> Adds error promoting to device loss when disallowed error occurs in a scope.
>
> - Defaults consume error calls to only allow validation and device loss
>   errors.
> - Allows OOM errors on Buffers, QuerySets, and Textures only.
> - Adds initial suite of unit tests (and any necessary updates to mock
>   framework).
>
> Bug: dawn:1336
> Change-Id: I82112ea6c147e894280e605bf8ae0ce00488c9f3
> Reviewed-on: https://dawn-review.googlesource.com/c/dawn/+/119800
> Reviewed-by: Austin Eng <enga@chromium.org>
> Commit-Queue: Loko Kung <lokokung@google.com>
> Kokoro: Kokoro <noreply+kokoro@google.com>

TBR=cwallez@chromium.org,enga@chromium.org,noreply+kokoro@google.com,dawn-scoped@luci-project-accounts.iam.gserviceaccount.com,lokokung@google.com

Change-Id: I7311be8aca739a78ec33caf9f8c12bbbf129cb1a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: dawn:1336