Update patch set 8
Patch Set 8:

I find "MemoryBarrier" conflicts with a Macro defined in Windows, so Dawn cannot be built when we enable OpenGL backend on Windows.

Here is the error log I got:

../../src/dawn_native/opengl/CommandBufferGL.cpp(507,24):  error: no member named '__faststorefence' in 'dawn_native::opengl::OpenGLFunctions'
                    gl.MemoryBarrier(GL_ALL_BARRIER_BITS);
                    ~~ ^
..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um\winnt.h(3304,23):  note: expanded from macro 'MemoryBarrier'
#define MemoryBarrier __faststorefence

Patch-set: 8
CC: Gerrit User 1000019 <1000019@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>