Create patch set 10
Change has been successfully rebased and submitted as d9f659670d1d72d33a803029729a7cbb6eb275cc

7 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: src/tint/reader/wgsl/parser_impl.cc
Insertions: 5, Deletions: 7.

@@ -1672,18 +1672,19 @@
     if (attrs.errored) {
         return Failure::kErrored;
     }
-    return expect_compound_statement(std::move(attrs.value), use);
+    return expect_compound_statement(attrs.value, use);
 }
 
 // compound_statement
 //   : attribute* BRACE_LEFT statement* BRACE_RIGHT
-Expect<ast::BlockStatement*> ParserImpl::expect_compound_statement(AttributeList attrs,
+Expect<ast::BlockStatement*> ParserImpl::expect_compound_statement(AttributeList& attrs,
                                                                    std::string_view use) {
     return expect_brace_block(use, [&]() -> Expect<ast::BlockStatement*> {
         auto stmts = expect_statements();
         if (stmts.errored) {
             return Failure::kErrored;
         }
+        TINT_DEFER(attrs.Clear());
         return create<ast::BlockStatement>(Source{}, stmts.value, std::move(attrs));
     });
 }
@@ -1746,6 +1747,7 @@
     if (attrs.errored) {
         return Failure::kErrored;
     }
+    TINT_DEFER(expect_attributes_consumed(attrs.value));
 
     // Non-block statements that error can resynchronize on semicolon.
     auto stmt = sync(Token::Type::kSemicolon, [&] { return non_block_statement(); });
@@ -1797,17 +1799,13 @@
     }
 
     if (peek_is(Token::Type::kBraceLeft)) {
-        auto body = expect_compound_statement(std::move(attrs.value), "block statement");
+        auto body = expect_compound_statement(attrs.value, "block statement");
         if (body.errored) {
             return Failure::kErrored;
         }
         return body.value;
     }
 
-    if (!expect_attributes_consumed(attrs.value)) {
-        return Failure::kErrored;
-    }
-
     return Failure::kNoMatch;
 }
 
```
```
The name of the file: src/tint/reader/wgsl/parser_impl.h
Insertions: 1, Deletions: 1.

@@ -549,7 +549,7 @@
     /// @param attrs the list of attributes for the statement
     /// @param use a description of what was being parsed if an error was raised
     /// @returns the parsed statements
-    Expect<ast::BlockStatement*> expect_compound_statement(AttributeList attrs,
+    Expect<ast::BlockStatement*> expect_compound_statement(AttributeList& attrs,
                                                            std::string_view use);
     /// Parses a `paren_expression` grammar element, erroring on parse failure.
     /// @returns the parsed element or nullptr
```
```
The name of the file: test/tint/diagnostic_filtering/default_case_body_attribute.wgsl.expected.fxc.hlsl
Insertions: 0, Deletions: 1.

@@ -18,7 +18,6 @@
 };
 
 void main_inner(float x) {
-  int(x);
   do {
   } while (false);
 }
```
```
The name of the file: src/tint/reader/wgsl/parser_impl_statement_test.cc
Insertions: 10, Deletions: 0.

@@ -358,5 +358,15 @@
     EXPECT_EQ(sa->condition->source.range.end.column, 20u);
 }
 
+TEST_F(ParserImplTest, Statement_UnexpectedAttributes) {
+    auto p = parser("@diagnostic(off, derivative_uniformity) return;");
+    auto e = p->statement();
+    EXPECT_TRUE(p->has_error());
+    EXPECT_FALSE(e.errored);
+    EXPECT_TRUE(e.matched);
+    EXPECT_NE(e.value, nullptr);
+    EXPECT_EQ(p->error(), "1:2: unexpected attributes");
+}
+
 }  // namespace
 }  // namespace tint::reader::wgsl
```
```
The name of the file: test/tint/diagnostic_filtering/default_case_body_attribute.wgsl.expected.dxc.hlsl
Insertions: 0, Deletions: 12.

@@ -1,5 +1,3 @@
-SKIP: triggers crbug.com/tint/1820
-
 diagnostic_filtering/default_case_body_attribute.wgsl:8:11 warning: 'textureSample' must only be called from uniform control flow
       _ = textureSample(t, s, vec2(0, 0));
           ^^^^^^^^^^^^^
@@ -20,7 +18,6 @@
 };
 
 void main_inner(float x) {
-  int(x);
   do {
   } while (false);
 }
@@ -29,12 +26,3 @@
   main_inner(tint_symbol.x);
   return;
 }
-DXC validation failure:
-shader.hlsl:9:7: error: redefinition of 'x' with a different type: 'int' vs 'float'
-  int(x);
-      ^
-shader.hlsl:8:23: note: previous definition is here
-void main_inner(float x) {
-                      ^
-
-
```
```
The name of the file: src/tint/ast/block_statement_test.cc
Insertions: 14, Deletions: 0.

@@ -12,6 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+#include "gmock/gmock.h"
 #include "gtest/gtest-spi.h"
 #include "src/tint/ast/discard_statement.h"
 #include "src/tint/ast/if_statement.h"
@@ -40,6 +41,19 @@
     EXPECT_EQ(src.range.begin.column, 2u);
 }
 
+TEST_F(BlockStatementTest, Creation_WithAttributes) {
+    auto* d = create<DiscardStatement>();
+    auto* ptr = d;
+
+    auto* attr1 = DiagnosticAttribute(ast::DiagnosticSeverity::kOff, Expr("foo"));
+    auto* attr2 = DiagnosticAttribute(ast::DiagnosticSeverity::kOff, Expr("bar"));
+    auto* b = create<BlockStatement>(utils::Vector{d}, utils::Vector{attr1, attr2});
+
+    ASSERT_EQ(b->statements.Length(), 1u);
+    EXPECT_EQ(b->statements[0], ptr);
+    EXPECT_THAT(b->attributes, testing::ElementsAre(attr1, attr2));
+}
+
 TEST_F(BlockStatementTest, IsBlock) {
     auto* b = create<BlockStatement>(utils::Empty, utils::Empty);
     EXPECT_TRUE(b->Is<BlockStatement>());
```


Patch-set: 10
Patch-set-description: Rebase
Subject: tint: Handle @diagnostic on block statements
Status: merged
Commit: d9f659670d1d72d33a803029729a7cbb6eb275cc
Tag: autogenerated:gerrit:merged
Groups: 42ee1b65b4d18337026546a99963f0a7ef7eb0ff
Label: Code-Review=+2, 5c475f0788f2f8384b37347a9b5ccc858e3c174a Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Commit-Queue=+2, 6da6c783147e0598004d1a95e99faab6fa72d009 Gerrit User 1002241 <1002241@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Kokoro=+1, 06e5e46e80e348a688b0b75a77ed0c8e841cdc8f Gerrit User 1002476 <1002476@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: SUBM=+1, 050709a58c6fd87c083921c0b888fea793c75ed5
Submission-id: 118000
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Code-Review: Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Commit-Queue: Gerrit User 1002241 <1002241@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Auto-Submit
Submitted-with: MAY: Kokoro: Gerrit User 1002476 <1002476@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 1002241 \u003c1002241@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd\u003e","operation":"REMOVE","reason":"Change was submitted"}