tint/cmake: disable missing-variable-declarations warning
This fails AppleClang 12 builds, but passes on versions 13+. Our Dawn
build bots with MacOS 10 install AppleClang 12, and fail to build with
this warning when compiling an absl header:

In file included from /opt/s/w/ir/cache/uncached/dawn/third_party/abseil-cpp/absl/base/nullability.h:153:
/opt/s/w/ir/cache/uncached/dawn/third_party/abseil-cpp/absl/base/internal/nullability_impl.h:43:16: error: no previous extern declaration for non-static variable 'IsSupportedType<T *>' [-Werror,-Wmissing-variable-declarations]
constexpr bool IsSupportedType<T*> = true;
               ^

Change-Id: I0e187ebba44745a96bc8962dedfb978c38346abb