Update patch set 5
Change has been successfully rebased and submitted as e892da2abf9c2f436c8ba0c0eb70bff4ef4524cb

3 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: src/dawn/node/README.md
Insertions: 8, Deletions: 5.

@@ -59,13 +59,16 @@
 Now you can run CTS:
 
 ```sh
-./tools/run run-cts --dawn-node=<path-to-cts.js> [WebGPU CTS query]
+./tools/run run-cts --bin=<path-build-dir> [WebGPU CTS query]
 ```
 
+Where `<path-build-dir>` is the output directory. \
+Note: `<path-build-dir>` can be omitted if your build directory sits at `<dawn>/out/active`, which is enforced if you use `<dawn>/tools/setup-build` (recommended).
+
 Or if you checked out your own CTS repo:
 
 ```sh
-./tools/run run-cts --dawn-node=<path-to-cts.js> --cts=<path-to-cts> [WebGPU CTS query]
+./tools/run run-cts --bin=<path-build-dir> --cts=<path-to-cts> [WebGPU CTS query]
 ```
 
 If this fails with the error message `TypeError: expander is not a function or its return value is not iterable`, try appending `--build=false` to the start of the `run-cts` command line flags.
@@ -73,7 +76,7 @@
 To test against SwiftShader instead of the default Vulkan device, prefix `./tools/run run-cts` with `VK_ICD_FILENAMES=<swiftshader-cmake-build>/Linux/vk_swiftshader_icd.json`. For example:
 
 ```sh
-VK_ICD_FILENAMES=<swiftshader-cmake-build>/Linux/vk_swiftshader_icd.json ./tools/run run-cts --dawn-node=<path-to-cts.js> [WebGPU CTS query]
+VK_ICD_FILENAMES=<swiftshader-cmake-build>/Linux/vk_swiftshader_icd.json ./tools/run run-cts --bin=<path-build-dir> [WebGPU CTS query]
 ```
 
 The `--flag` parameter must be passed in multiple times, once for each flag begin set. Here are some common arguments:
@@ -87,7 +90,7 @@
 For example, on Windows, to use the d3dcompiler_47.dll from a Chromium checkout, and to dump shader output, we could run the following using Git Bash:
 
 ```sh
-./tools/run run-cts --verbose --dawn-node=/c/src/dawn/node/cts.js --cts=/c/src/webgpu-cts --flag=dlldir="C:\src\chromium\src\out\Release" --flag=enable-dawn-features=dump_shaders 'webgpu:shader,execution,builtin,abs:integer_builtin_functions,abs_unsigned:storageClass="storage";storageMode="read_write";containerType="vector";isAtomic=false;baseType="u32";type="vec2%3Cu32%3E"'
+./tools/run run-cts --verbose --bin=/c/src/dawn/out/active --cts=/c/src/webgpu-cts --flag=dlldir="C:\src\chromium\src\out\Release" --flag=enable-dawn-features=dump_shaders 'webgpu:shader,execution,builtin,abs:integer_builtin_functions,abs_unsigned:storageClass="storage";storageMode="read_write";containerType="vector";isAtomic=false;baseType="u32";type="vec2%3Cu32%3E"'
 ```
 
 Note that we pass `--verbose` above so that all test output, including the dumped shader, is written to stdout.
@@ -169,7 +172,7 @@
 Replacing:
 
 - `[cts-root]` with the path to the CTS root directory. If you are editing the `.vscode/launch.json` from within the CTS workspace, then you may use `${workspaceFolder}`.
-- `[cts.js]` this is the path to the `cts.js` module copied by the [build step](#Build)
+- `[cts.js]` this is the path to the `cts.js` file that should be copied to the output directory by the [build step](#build)
 - `test-query` with the test query string. Example: `webgpu:shader,execution,builtin,abs:*`
 
 ## Debugging dawn-node issues in gdb/lldb
```


Patch-set: 5
Subject: [tools] Fix CTS runner
Status: merged
Commit: e892da2abf9c2f436c8ba0c0eb70bff4ef4524cb
Tag: autogenerated:gerrit:merged
Groups: b44e8587e2c0d7d2b235d5a9f2a0c30484efede0
Label: Code-Review=+2, 2730b977f12196fd93605aa6940eb49c3556c948 Gerrit User 1002241 <1002241@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Commit-Queue=+2, 184876fd92f077dcc82b99fbdbc9a84c45707937 Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Auto-Submit=+1, 1fa65604570f17069991a23c451c6a8241d132a1 Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: Kokoro=+1, 16e6bb2c008698999497d6b3473c92883c094245 Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Label: SUBM=+1, b0084ac664351223e205669aeb4d71a2e3535b88
Submission-id: 147962
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Bot-Commit
Submitted-with: MAY: Code-Review: Gerrit User 1002241 <1002241@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Owners-Override
Submitted-with: MAY: Commit-Queue: Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Auto-Submit: Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: MAY: Kokoro: Gerrit User 1001737 <1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd>
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 1000002 \u003c1000002@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1002241 \u003c1002241@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1001737 \u003c1001737@dd02978d-1a8e-36d7-bcc0-a5723e5c0abd\u003e","operation":"REMOVE","reason":"Change was submitted"}